site_name: Python - MEB Bilgisayar Bilimi (Kur-1)

theme:
  name: material

nav:
  - Ana Sayfa: index.md

  - 10. Listeler:
      - 10.1 Liste Kavramı: 10_listeler/10_1_liste_kavrami__list_concept.md
      - 10.2 Liste Oluşturma: 10_listeler/10_2_liste_olusturma__create_list.md
      - 10.3 Eleman Ekleme: 10_listeler/10_3_eleman_ekleme.md
