site_name: "Python - MEB Bilgisayar Bilimi (Kur-1)"
site_url: "https://mehmetpeker.github.io/10-Sinif-Bilgisayar-Bilimi-Python/"
site_description: "MEB Bilgisayar Bilimi (Kur-1) için pedagojik ders notları ve örnekler."

theme:
  name: material
  language: tr
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - content.code.copy
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji

nav:
  - Ana Sayfa: index.md

  - 1. Python ile Programlamanın Temelleri:
      - 1.1 Giriş: 01_temeller/01_1_giris.md

  - 2. Değerler ve Değişkenler:
      - 2.1 Değer Nedir?: 02_degerler_ve_degiskenler/02_1_deger_nedir.md

  - 3. İfadeler ve Aritmetik İşlemler:
      - 3.1 Aritmetik: 03_aritmetik/03_1_aritmetik.md

  - 4. Koşullu Durumlar (if):
      - 4.1 if-else: 04_kosullar/04_1_if_else.md

  - 5. Döngüler:
      - 5.1 for: 05_donguler/05_1_for.md

  - 6. Fonksiyonlar 1:
      - 6.1 Fonksiyon Mantığı: 06_fonksiyonlar1/06_1_fonksiyon.md

  - 7. Fonksiyon Yazma:
      - 7.1 Parametre: 07_fonksiyon_yazma/07_1_parametre.md

  - 8. Fonksiyonlar 2:
      - 8.1 Return: 08_fonksiyonlar2/08_1_return.md

  - 9. Nesneler:
      - 9.1 Nesne Mantığı: 09_nesneler/09_1_nesne.md

  - 10. Listeler:
      - Ders Planı: 10_listeler/ders_plani.md
      - 10.1 Liste Kavramı: 10_listeler/10_1_liste_kavrami.md
      - 10.2 Liste Oluşturmak: 10_listeler/10_2_liste_olusturma__create_list.md
      - 10.3 list() Fonksiyonu: 10_listeler/10_3_list_fonksiyonu.md
      - 10.4 * Operatörü: 10_listeler/10_4_carpma_operatoru.md
      - 10.5 Üyelik (in): 10_listeler/10_5_uyelik_in.md
      - 10.6 Atama & Eşitleme: 10_listeler/10_6_atama_esitleme.md
      - 10.7 Sınırlar: 10_listeler/10_7_sinirlar.md
      - 10.8 Dilimleme: 10_listeler/10_8_dilimleme.md
      - 10.9 Eleman Çıkarma: 10_listeler/10_9_eleman_cikarma.md
      - 10.10 Listeler & Fonksiyonlar: 10_listeler/10_10_listeler_fonksiyonlar.md
      - 10.11 Metotlar: 10_listeler/10_11_metotlar.md
      - 10.12 Çok Boyutlu Listeler: 10_listeler/10_12_cok_boyutlu_listeler.md
      - 10.13 Çok Boyutlu Diziler: 10_listeler/10_13_cok_boyutlu_diziler.md
      - 10.14 _ Sembolü: 10_listeler/10_14_altcizgi_sembolu.md
      - 10.15 Özet: 10_listeler/10_15_ozet.md
